## Bài 1

In [73]:
import torch
a = torch.tensor(
[[1, 2, 3],
[4, 5, 6]],
dtype=torch.int32
)
print(a)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


## Bài 2

In [74]:
import torch
a = torch.rand(3, 4)
b = torch.randn(3, 4)
c = torch.zeros(2, 3)
d = torch.ones(2, 3)
e = torch.eye(4)
print(a)
print(b)
print(c)
print(d)
print(e)

tensor([[0.0754, 0.0985, 0.1449, 0.8861],
        [0.8505, 0.0297, 0.8914, 0.4781],
        [0.0703, 0.5831, 0.0929, 0.4840]])
tensor([[-1.0761, -0.4571, -1.2262,  2.1491],
        [-0.3007, -0.2117, -0.5815,  0.8940],
        [ 2.3072, -1.0469,  1.6454,  0.1082]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


In [75]:
f = torch.full((5, 5), 10)
print(f)

tensor([[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]])


## Bài 3

In [76]:
import torch
a = torch.zeros(2, 3, 4)
print("Tensor:")
print(a)
print("Shape:", a.shape)
print("Size:", a.size())
print("Number of dimensions:", a.ndim)
print("Data type:", a.dtype)

Tensor:
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
Shape: torch.Size([2, 3, 4])
Size: torch.Size([2, 3, 4])
Number of dimensions: 3
Data type: torch.float32


## Bài 4

In [77]:
import torch
a = torch.randn(3, 4, 5)
print("Original tensor:")
print(a)
print("\nTensor a[1]:")
print(a[1])
print("\nTensor a[1:, 2:4]:")
print(a[1:, 2:4])

Original tensor:
tensor([[[-0.1140,  0.9583,  0.7419, -0.5468,  1.1880],
         [ 0.8289, -0.6418, -1.0069, -0.5047, -0.0947],
         [-0.8464, -0.2162, -0.7560, -0.2341, -0.4327],
         [-0.2340, -1.1702, -0.1224, -1.1599,  0.5262]],

        [[-0.0686,  2.6092,  0.2932,  0.2036, -1.9880],
         [-0.7624,  0.5735, -0.4371, -0.6559,  1.8464],
         [ 2.9214,  1.1753,  0.6491,  1.1336, -0.0077],
         [-1.6810,  0.9214,  1.1656, -0.2199, -0.0610]],

        [[ 0.5297, -0.8953,  0.1424, -0.7299,  0.8243],
         [ 0.0861, -0.6291, -1.7213,  2.5022, -0.5255],
         [ 0.1851, -0.3454,  0.1520, -0.6139,  0.0055],
         [-0.1068, -0.3155, -0.8796, -2.3230, -0.5074]]])

Tensor a[1]:
tensor([[-0.0686,  2.6092,  0.2932,  0.2036, -1.9880],
        [-0.7624,  0.5735, -0.4371, -0.6559,  1.8464],
        [ 2.9214,  1.1753,  0.6491,  1.1336, -0.0077],
        [-1.6810,  0.9214,  1.1656, -0.2199, -0.0610]])

Tensor a[1:, 2:4]:
tensor([[[ 2.9214,  1.1753,  0.6491,  1.1336, -0.0

In [78]:
print("\nTensor a[:, :, -2:]:")
print(a[:, :, -2:])


Tensor a[:, :, -2:]:
tensor([[[-0.5468,  1.1880],
         [-0.5047, -0.0947],
         [-0.2341, -0.4327],
         [-1.1599,  0.5262]],

        [[ 0.2036, -1.9880],
         [-0.6559,  1.8464],
         [ 1.1336, -0.0077],
         [-0.2199, -0.0610]],

        [[-0.7299,  0.8243],
         [ 2.5022, -0.5255],
         [-0.6139,  0.0055],
         [-2.3230, -0.5074]]])


## Bài 5

In [79]:
import torch
a = torch.randn(3, 4)
print("Original:")
print(a)
print("\nFlatten:")
print(a.ravel())
print("\nReshape to 3 x 2 x 2:")
print(a.reshape(3, 2, 2))

Original:
tensor([[ 1.2453,  1.6353, -0.5084,  2.0902],
        [ 0.4698, -0.3187, -1.4534, -0.7641],
        [ 0.3368, -1.4190, -1.1950, -1.0611]])

Flatten:
tensor([ 1.2453,  1.6353, -0.5084,  2.0902,  0.4698, -0.3187, -1.4534, -0.7641,
         0.3368, -1.4190, -1.1950, -1.0611])

Reshape to 3 x 2 x 2:
tensor([[[ 1.2453,  1.6353],
         [-0.5084,  2.0902]],

        [[ 0.4698, -0.3187],
         [-1.4534, -0.7641]],

        [[ 0.3368, -1.4190],
         [-1.1950, -1.0611]]])


In [80]:
print("\nReshape to 2 x 6:")
print(a.reshape(2, 6))


Reshape to 2 x 6:
tensor([[ 1.2453,  1.6353, -0.5084,  2.0902,  0.4698, -0.3187],
        [-1.4534, -0.7641,  0.3368, -1.4190, -1.1950, -1.0611]])


## Bài 6

In [81]:
import torch
a = torch.randn(2, 3)
b = torch.randn(2, 3)
print("a:")
print(a)
print("b:")
print(b)
print("\na + b:")
print(a + b)
print("\na / b:")
print(a / b)
print("\na^2:")
print(a ** 2)
print("\nMatrix multiplication:")
print(a @ b.T)

a:
tensor([[-1.4588, -1.0267,  0.3089],
        [ 2.1847,  0.5242,  0.1800]])
b:
tensor([[ 1.4488,  0.1866,  0.8361],
        [ 1.3312,  0.7340, -0.6278]])

a + b:
tensor([[-0.0100, -0.8401,  1.1451],
        [ 3.5159,  1.2583, -0.4478]])

a / b:
tensor([[-1.0069, -5.5010,  0.3695],
        [ 1.6411,  0.7141, -0.2867]])

a^2:
tensor([[2.1282, 1.0542, 0.0954],
        [4.7730, 0.2748, 0.0324]])

Matrix multiplication:
tensor([[-2.0468, -2.8896],
        [ 3.4135,  3.1802]])


## Bài 7

In [82]:
import torch
a = torch.randn(3, 4)
print(a)
print("\nMean:")
print(torch.mean(a, dim=0))
print("\nStandard deviation:")
print(torch.std(a, dim=0))
print("\nCumulative sum:")
print(torch.cumsum(a, dim=0))

tensor([[ 1.1686,  0.3411,  0.2788, -1.1595],
        [-0.1181, -0.4662, -0.3932,  0.9652],
        [ 0.6037,  0.2015, -0.9343, -0.8767]])

Mean:
tensor([ 0.5514,  0.0255, -0.3496, -0.3570])

Standard deviation:
tensor([0.6449, 0.4315, 0.6077, 1.1538])

Cumulative sum:
tensor([[ 1.1686,  0.3411,  0.2788, -1.1595],
        [ 1.0505, -0.1251, -0.1144, -0.1943],
        [ 1.6543,  0.0764, -1.0487, -1.0710]])


In [83]:
import torch
a = torch.randn(3, 4)
print(a)
print("\nMean:")
print(torch.mean(a, dim=1))
print("\nStandard deviation:")
print(torch.std(a, dim=1))
print("\nCumulative sum:")
print(torch.cumsum(a, dim=1))

tensor([[-1.0588,  0.4309,  1.8777,  1.3487],
        [ 1.3624, -0.2719, -0.4077, -1.1204],
        [ 0.1724,  0.0115,  0.5649,  0.3488]])

Mean:
tensor([ 0.6496, -0.1094,  0.2744])

Standard deviation:
tensor([1.2863, 1.0494, 0.2377])

Cumulative sum:
tensor([[-1.0588, -0.6279,  1.2498,  2.5985],
        [ 1.3624,  1.0905,  0.6828, -0.4376],
        [ 0.1724,  0.1839,  0.7489,  1.0977]])


## Bài 8

In [84]:
import torch
x = torch.tensor(
3.6,
requires_grad=True
)
y = x * x
y.backward()
print("x =", x)
print("y =", y)
print("x.grad =", x.grad)

x = tensor(3.6000, requires_grad=True)
y = tensor(12.9600, grad_fn=<MulBackward0>)
x.grad = tensor(7.2000)


In [85]:
import torch
x = torch.tensor(
3.6,
requires_grad=True
)
y = 3*x**2 + 2*x + 1
y.backward()
print("x =", x)
print("y =", y)
print("x.grad =", x.grad)

x = tensor(3.6000, requires_grad=True)
y = tensor(47.0800, grad_fn=<AddBackward0>)
x.grad = tensor(23.6000)


## Bài 9

In [86]:
import numpy as np
import torch
polynomial = np.poly1d([1, 2, 3])
N = 20
X = np.random.randn(N, 1) * 5
Y = polynomial(X)
XX = np.hstack([
X * X,
X,
np.ones_like(X)
])
w = torch.randn(3, 1, requires_grad=True)
x = torch.tensor(XX, dtype=torch.float32)
y = torch.tensor(Y, dtype=torch.float32)
optimizer = torch.optim.NAdam([w], lr=0.01)
print("Initial coefficients:")
print(w)
for epoch in range(1000):
    optimizer.zero_grad()
    y_pred = x @ w
    mse = torch.mean(torch.square(y - y_pred))
    mse.backward()
    optimizer.step()
print("Learned coefficients:")
print(w)

Initial coefficients:
tensor([[-0.5474],
        [ 0.2689],
        [ 0.2200]], requires_grad=True)
Learned coefficients:
tensor([[1.0104],
        [1.9930],
        [2.0870]], requires_grad=True)


## Bài 10

In [87]:
import random
import torch
A = torch.tensor(random.random(), requires_grad=True)
B = torch.tensor(random.random(), requires_grad=True)
C = torch.tensor(random.random(), requires_grad=True)
D = torch.tensor(random.random(), requires_grad=True)
EPOCHS = 2000
optimizer = torch.optim.NAdam([A, B, C, D], lr=0.01)
for _ in range(EPOCHS):
    y1 = A + B - 9
    y2 = C - D - 1
    y3 = A + C - 8
    y4 = B - D - 2
    sqerr = y1*y1 + y2*y2 + y3*y3 + y4*y4
    optimizer.zero_grad()
    sqerr.backward()
    optimizer.step()
print("A =", A)
print("B =", B)
print("C =", C)
print("D =", D)

A = tensor(4.4458, requires_grad=True)
B = tensor(4.5542, requires_grad=True)
C = tensor(3.5542, requires_grad=True)
D = tensor(2.5542, requires_grad=True)


## Bài 11

## a:

In [88]:
import torch
x = torch.randn(24)
print("\nReshape to 4 x 6:")
print(x.reshape(4, 6))
print("\nReshape to 2 x 12:")
print(x.reshape(2, 12))
print("\nReshape to 2 x 3 x 4:")
print(x.reshape(2, 3, 4))


Reshape to 4 x 6:
tensor([[ 1.2488,  1.3457, -0.7537,  0.5786, -1.2521,  0.4290],
        [ 1.5027, -1.0356, -2.3724, -1.5551, -1.3492, -0.3317],
        [-0.3440,  1.9742,  0.4410,  0.4400, -1.2235, -0.5048],
        [-0.9613,  0.6514, -1.4606, -0.8266,  0.2292, -0.8130]])

Reshape to 2 x 12:
tensor([[ 1.2488,  1.3457, -0.7537,  0.5786, -1.2521,  0.4290,  1.5027, -1.0356,
         -2.3724, -1.5551, -1.3492, -0.3317],
        [-0.3440,  1.9742,  0.4410,  0.4400, -1.2235, -0.5048, -0.9613,  0.6514,
         -1.4606, -0.8266,  0.2292, -0.8130]])

Reshape to 2 x 3 x 4:
tensor([[[ 1.2488,  1.3457, -0.7537,  0.5786],
         [-1.2521,  0.4290,  1.5027, -1.0356],
         [-2.3724, -1.5551, -1.3492, -0.3317]],

        [[-0.3440,  1.9742,  0.4410,  0.4400],
         [-1.2235, -0.5048, -0.9613,  0.6514],
         [-1.4606, -0.8266,  0.2292, -0.8130]]])


## b:

In [89]:
import torch
a = torch.randn(3, 4)
b = torch.randn(3, 4)
print("A = ", a)
print("B = ", b)
print("A + B = ", a + b)
print("A * B = ", a * b)
print("A / B = ", a / b)
print("Mean A: ", torch.mean(a, dim = 0))
print("Mean B: ", torch.mean(b, dim = 0))
print("Std A: ", torch.std(a, dim = 0))
print("Std B: ", torch.std(b, dim = 0))

A =  tensor([[ 0.9562,  0.0592, -0.6571,  1.7000],
        [ 0.2746, -0.6264, -0.5176,  1.7932],
        [ 1.6549,  2.3439,  0.6113, -1.1055]])
B =  tensor([[ 1.1230,  0.5655, -0.7886,  1.2877],
        [ 0.5048, -0.4680, -0.7658, -0.2287],
        [-0.4090, -1.6641,  0.0800, -1.2725]])
A + B =  tensor([[ 2.0792,  0.6248, -1.4457,  2.9877],
        [ 0.7794, -1.0944, -1.2834,  1.5645],
        [ 1.2459,  0.6798,  0.6913, -2.3780]])
A * B =  tensor([[ 1.0738,  0.0335,  0.5182,  2.1891],
        [ 0.1386,  0.2932,  0.3964, -0.4101],
        [-0.6768, -3.9005,  0.0489,  1.4068]])
A / B =  tensor([[ 0.8514,  0.1048,  0.8333,  1.3202],
        [ 0.5440,  1.3386,  0.6759, -7.8413],
        [-4.0466, -1.4085,  7.6390,  0.8688]])
Mean A:  tensor([ 0.9619,  0.5922, -0.1878,  0.7959])
Mean B:  tensor([ 0.4063, -0.5222, -0.4914, -0.0712])
Std A:  tensor([0.6902, 1.5553, 0.6956, 1.6473])
Std B:  tensor([0.7707, 1.1158, 0.4950, 1.2874])


## c:

In [90]:
import torch
x = torch.tensor(
2.0,
requires_grad=True
)
y = 2 * x**2 + 5 * x + 3
y.backward()
print("x =", x)
print("y =", y)
print("x.grad =", x.grad)

x = tensor(2., requires_grad=True)
y = tensor(21., grad_fn=<AddBackward0>)
x.grad = tensor(13.)


## d:

In [92]:
import torch
import numpy as np
polynomial = np.poly1d([2, -3, 5])
N = 20
X = np.random.randn(N, 1) * 5
Y = polynomial(X)
XX = np.hstack([
X * X,
X,
np.ones_like(X)
])
w = torch.randn(3, 1, requires_grad=True)
x = torch.tensor(XX, dtype=torch.float32)
y = torch.tensor(Y, dtype=torch.float32)
optimizer = torch.optim.NAdam([w], lr=0.01)
print("Initial coefficients:")
print(w)
for epoch in range(1000):
    optimizer.zero_grad()
    y_pred = x @ w
    mse = torch.mean(torch.square(y - y_pred))
    mse.backward()
    optimizer.step()
print("Learned coefficients:")
print(w)

Initial coefficients:
tensor([[ 0.0357],
        [-1.2325],
        [-0.2825]], requires_grad=True)
Learned coefficients:
tensor([[ 2.0193],
        [-2.9790],
        [ 2.3094]], requires_grad=True)
